name: "rnd"
buffer_capacity: 1000000
activation: "relu"
discount: 0.99
batch_size: 256
seed: 42
seed_steps: 4000

# critic
critic_hidden_dimension: 256
critic_hidden_layers: 2
critic_learning_rate: 0.0001
critic_target_update_frequency: 2
critic_tau: 0.01

# actor
actor_hidden_dimension: 256
actor_hidden_layers: 2
actor_learning_rate: 0.0001
actor_update_frequency: 1
std_dev_clip: 0.3
std_dev_schedule: 0.2

# rnd
rnd_representation_dimension: 256
rnd_hidden_dimension: 256
rnd_scale: 1.0
